# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Make & Releases

on: # 流水线执行的时机
  push:
    branches: [ "main" ]
  pull_request: # 执行 pr 且 target 是 main
    branches: [ "main" ]

jobs:
  make:  # 工作流的名称
    runs-on: macos-latest # 在哪种系统的虚拟机运行

    strategy: # 对作业使用矩阵策略,如在多个版本的多个操作系统上运行
      matrix: # 上下文
        node-version: [19.x]

    steps:
    # uses 执行 github 的内置命令；name 可以为每个 step 取个名字，可省略
    - uses: actions/checkout@v3  # 将代码签出到运行机器
    - name: Install Node Version ${{ matrix.node-version }} # 步骤
      uses: actions/setup-node@v3 # 为虚拟机安装 Node 环境
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install # 运行命令
    - run: npm run make

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: out
